# Generated by Django 5.2.7 on 2025-10-26 19:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('decano', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contacto_responsable', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='facultades/')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PracticaInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_servicio', models.CharField(choices=[('investigacion', 'Investigación'), ('docencia', 'Docencia'), ('administrativo', 'Administrativo'), ('tecnico', 'Técnico'), ('social', 'Servicio Social'), ('otro', 'Otro')], max_length=20)),
                ('requisitos', models.TextField()),
                ('duracion_semanas', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('horas_semana', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cupos_disponibles', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cupos_totales', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='disponible', max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_inscripcion', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios para el estudiante')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.facultad')),
            ],
            options={
                'verbose_name': 'Práctica Interna',
                'verbose_name_plural': 'Prácticas Internas',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_evaluacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.estudiante')),
                ('evaluado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripciones_internas_evaluadas', to=settings.AUTH_USER_MODEL)),
                ('practica_interna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.practicainterna')),
            ],
            options={
                'verbose_name': 'Inscripción Interna',
                'verbose_name_plural': 'Inscripciones Internas',
                'ordering': ['-fecha_inscripcion'],
                'unique_together': {('estudiante', 'practica_interna')},
            },
        ),
    ]
