# Generated by Django 5.2.7 on 2025-11-07 05:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='area',
            field=models.CharField(choices=[('tecnologia', 'Tecnología e Informática'), ('salud', 'Ciencias de la Salud'), ('educacion', 'Educación'), ('administracion', 'Administración y Negocios'), ('ingenieria', 'Ingeniería'), ('derecho', 'Derecho y Ciencias Jurídicas'), ('comunicacion', 'Comunicación y Marketing'), ('turismo', 'Turismo y Hotelería'), ('agronomia', 'Agronomía y Veterinaria'), ('arte', 'Arte y Diseño'), ('otro', 'Otro')], default='otro', help_text='Área académica de la práctica', max_length=50),
        ),
        migrations.AddField(
            model_name='practica',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', help_text='Modalidad de trabajo', max_length=20),
        ),
        migrations.AddField(
            model_name='practicainterna',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', help_text='Modalidad de trabajo', max_length=20),
        ),
        migrations.AlterField(
            model_name='practica',
            name='duracion_semanas',
            field=models.IntegerField(help_text='Duración en semanas (1-52)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='practica',
            name='horas_semana',
            field=models.IntegerField(help_text='Horas por semana (1-40)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='practicainterna',
            name='duracion_semanas',
            field=models.IntegerField(help_text='Duración en semanas (1-52)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)]),
        ),
        migrations.AlterField(
            model_name='practicainterna',
            name='horas_semana',
            field=models.IntegerField(help_text='Horas por semana (1-40)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
