# Generated by Django 5.2.7 on 2025-11-07 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_practica_area_practica_modalidad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que aprobó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_constitucion',
            field=models.FileField(blank=True, help_text='Documento de constitución de la empresa (PDF)', null=True, upload_to='empresas/documentos/constitucion/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_representante',
            field=models.FileField(blank=True, help_text='Documento de identidad del representante legal (PDF)', null=True, upload_to='empresas/documentos/representante/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='documento_ruc',
            field=models.FileField(blank=True, help_text='Certificado de RUC (PDF)', null=True, upload_to='empresas/documentos/ruc/'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de aprobación por el administrador', max_length=20),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='observaciones_aprobacion',
            field=models.TextField(blank=True, help_text='Comentarios del administrador sobre la aprobación/rechazo'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, help_text='Administrador que aprobó el registro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facultades_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultad',
            name='documento_autorizacion',
            field=models.FileField(blank=True, help_text='Documento de autorización institucional (PDF)', null=True, upload_to='facultades/documentos/autorizacion/'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='documento_representante',
            field=models.FileField(blank=True, help_text='Documento de identidad del decano/responsable (PDF)', null=True, upload_to='facultades/documentos/representante/'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='documento_resolucion',
            field=models.FileField(blank=True, help_text='Resolución de creación de la facultad (PDF)', null=True, upload_to='facultades/documentos/resolucion/'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='estado_aprobacion',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', help_text='Estado de aprobación por el administrador', max_length=20),
        ),
        migrations.AddField(
            model_name='facultad',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='observaciones_aprobacion',
            field=models.TextField(blank=True, help_text='Comentarios del administrador sobre la aprobación/rechazo'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(help_text='RUC debe terminar en 001', max_length=11, unique=True),
        ),
    ]
