# Generated by Django 5.2.7 on 2025-11-07 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0006_empresa_aprobado_por_empresa_documento_constitucion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='ruc',
            field=models.CharField(help_text='RUC debe terminar en 001', max_length=13, unique=True),
        ),
    ]
