# Generated by Django 5.2.7 on 2025-11-07 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_alter_empresa_ruc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aprobacion_practica', '¡Felicidades! Has sido seleccionado'), ('rechazo_practica', 'Postulación no aceptada'), ('cancelacion_practica', 'Práctica cancelada'), ('actualizacion', 'Actualización de estado'), ('recordatorio', 'Recordatorio')], default='actualizacion', max_length=50)),
                ('titulo', models.CharField(help_text='Título de la notificación', max_length=200)),
                ('mensaje', models.TextField(help_text='Mensaje completo de la notificación')),
                ('leida', models.BooleanField(default=False, help_text='Marca si la notificación fue leída')),
                ('mostrada', models.BooleanField(default=False, help_text='Marca si se mostró el modal')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('inscripcion', models.ForeignKey(blank=True, help_text='Inscripción relacionada (práctica externa)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion')),
                ('inscripcion_interna', models.ForeignKey(blank=True, help_text='Inscripción relacionada (práctica interna)', null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcioninterna')),
                ('usuario', models.ForeignKey(help_text='Usuario que recibe la notificación', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='inscripcion_usuario_2160d6_idx'), models.Index(fields=['usuario', 'mostrada'], name='inscripcion_usuario_55757c_idx')],
            },
        ),
    ]
