# Generated by Django 5.2.7 on 2025-11-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0008_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud para Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud para Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud para Google Maps', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facultad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud para Google Maps', max_digits=10, null=True),
        ),
    ]
