# Generated by Django 5.2.7 on 2025-11-07 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0009_empresa_latitud_empresa_longitud_facultad_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tipo_titulo',
            field=models.CharField(blank=True, choices=[('licenciatura', 'Licenciatura'), ('ingenieria', 'Ingeniería')], help_text='Solo para egresados', max_length=20, null=True, verbose_name='Tipo de Título'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_usuario',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('egresado', 'Egresado')], default='estudiante', max_length=20, verbose_name='Tipo de Usuario'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ciclo_actual',
            field=models.IntegerField(blank=True, help_text='Solo para estudiantes activos', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Ciclo Actual'),
        ),
    ]
