# Generated by Django 5.2.7 on 2025-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0010_estudiante_tipo_titulo_estudiante_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practica',
            name='dirigido_a',
            field=models.CharField(choices=[('estudiantes', 'Solo Estudiantes Activos'), ('egresados', 'Solo Egresados'), ('ambos', 'Estudiantes y Egresados')], default='ambos', help_text='Tipo de postulante que puede aplicar', max_length=20, verbose_name='Dirigido a'),
        ),
        migrations.AddField(
            model_name='practicainterna',
            name='dirigido_a',
            field=models.CharField(choices=[('estudiantes', 'Solo Estudiantes Activos'), ('egresados', 'Solo Egresados'), ('ambos', 'Estudiantes y Egresados')], default='ambos', help_text='Tipo de postulante que puede aplicar', max_length=20, verbose_name='Dirigido a'),
        ),
    ]
