# Generated by Django 5.2.7 on 2025-11-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0011_practica_dirigido_a_practicainterna_dirigido_a'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoInscripcionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cv', 'Curriculum Vitae'), ('carta_presentacion', 'Carta de Presentación'), ('certificado_notas', 'Certificado de Notas'), ('carta_recomendacion', 'Carta de Recomendación'), ('otro', 'Otro')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='documentos_inscripcion_interna/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('inscripcion_interna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='inscripciones.inscripcioninterna')),
            ],
            options={
                'verbose_name': 'Documento de Inscripción Interna',
                'verbose_name_plural': 'Documentos de Inscripción Interna',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
